CREATE TABLE usuario(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) UNIQUE NOT NULL,
    email VARCHAR(250) UNIQUE NOT NULL,
    senha VARCHAR(250)  NOT NULL,
    funcao VARCHAR(100)  NOT NULL DEFAULT 'CLIENTE' CHECK(funcao IN ('VENDEDOR','ADMIN','CLIENTE')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criadoEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE produto(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(250) UNIQUE NOT NULL,
    descricao VARCHAR(300) NOT NULL,
    preco NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criadoEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estoque(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    produto BIGINT  NOT NULL  REFERENCES produto(id),
    quantidadeInicial BIGINT NOT NULL DEFAULT 0,
    quantidadeAtual  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE venda(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario BIGINT  NOT NULL REFERENCES usuario(id),
    statusPagamento VARCHAR(30) NOT NULL  CHECK(statusPagamento IN ('CONCLUIDO','PENDENTE','CANCELADO')),
    metodoPagamento VARCHAR(30) NOT NULL CHECK(metodoPagamento IN ('PIX','CARTAO')),
    pagamentoId BIGINT NOT NULL UNIQUE,
    dataVenda TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE itemVenda(
    id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    venda  BIGINT NOT NULL REFERENCES venda(id),
    produto  BIGINT NOT NULL REFERENCES produto(id),
    quantidade BIGINT  NOT NULL DEFAULT 0 ,
    preco NUMERIC(10,2) NOT NULL DEFAULT 0.00
);