CREATE TABLE usuario (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) UNIQUE NOT NULL,
    email VARCHAR(250) UNIQUE NOT NULL,
    senha VARCHAR(250) NOT NULL,
    funcao VARCHAR(100) NOT NULL DEFAULT 'CLIENTE' CHECK(funcao IN ('VENDEDOR','ADMIN','CLIENTE')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE produto (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(250) UNIQUE NOT NULL,
    descricao VARCHAR(300) NOT NULL,
    preco NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estoque (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES produto(id),
    quantidade_inicial NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    quantidade_atual NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE venda (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id),
    produto_id BIGINT NOT NULL REFERENCES produto(id),
    valor NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    quantidade NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    valor_total_vendas NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    data_venda TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE historico (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id),
    produto_id BIGINT NOT NULL REFERENCES produto(id),
    estoque_id BIGINT NOT NULL REFERENCES estoque(id),
    quantidade_retirada NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vendedor (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id),
    cpf VARCHAR(11) UNIQUE NOT NULL,
    data_nascimento DATE NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);