CREATE TABLE vendedor(
    id BIGINT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario BIGINT NOT NULL REFERENCES usuario(id),
    cpf VARCHAR(11) UNIQUE NOT NULL,
    dataNascimento VARCHAR(10) NOT NULL,
    criadoEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);