ALTER TABLE venda ADD COLUMN produto BIGINT NOT NULL REFERENCES produto(id);
ALTER TABLE venda ADD COLUMN valor NUMERIC(10,2) NOT NULL DEFAULT 0.0;
ALTER TABLE venda DROP COLUMN metodoPagamento;
ALTER TABLE venda DROP COLUMN pagamentoId;