SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE IF EXISTS historico CASCADE;
DROP TABLE IF EXISTS itemVenda CASCADE;
DROP TABLE IF EXISTS venda CASCADE;
DROP TABLE IF EXISTS estoque CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE usuario (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) UNIQUE NOT NULL,
    email VARCHAR(250) UNIQUE NOT NULL,
    senha VARCHAR(250) NOT NULL,
    funcao VARCHAR(100) NOT NULL DEFAULT 'CLIENTE' CHECK(funcao IN ('VENDEDOR','ADMIN','CLIENTE')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criadoEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE produto (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(250) UNIQUE NOT NULL,
    descricao VARCHAR(300) NOT NULL,
    preco NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criadoEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estoque (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    produto BIGINT NOT NULL REFERENCES produto(id),
    quantidadeInicial BIGINT NOT NULL DEFAULT 0,
    quantidadeAtual BIGINT NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE venda (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario BIGINT NOT NULL REFERENCES usuario(id),
    produto BIGINT NOT NULL REFERENCES produto(id),
    valor NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    statusPagamento VARCHAR(30) NOT NULL CHECK(statusPagamento IN ('CONCLUIDO','PENDENTE','CANCELADO')),
    dataVenda TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE historico (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario BIGINT NOT NULL REFERENCES usuario(id),
    produto BIGINT NOT NULL REFERENCES produto(id),
    estoque BIGINT NOT NULL REFERENCES estoque(id),
    criadoEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);